#ifndef CONFIG_H_
#define CONFIG_H_

// Display
#define CHIP8_DISPLAY_WIDTH 64
#define CHIP8_DISPLAY_HEIGHT 32
#define CHIP8_SPRITE_HEIGHT 5

// Memory
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_TOTAL_DATA_REGISERS 16
#define CHIP8_STACK_DEPTH 16
#define CHIP8_CHARSET_LOAD_ADDR 0x0000
#define CHIP8_PROGRAM_LOAD_ADDR 0x0200

// Keyboard
#define CHIP8_TOTAL_KEYS 16

// Emulator
#define EMULATOR_WINDOW_TITLE "Chip8 Emulator"
#define EMULATOR_WINDOW_SCALE 10
#define EMULATOR_WINDOW_WIDTH CHIP8_DISPLAY_WIDTH * EMULATOR_WINDOW_SCALE
#define EMULATOR_WINDOW_HEIGHT CHIP8_DISPLAY_HEIGHT * EMULATOR_WINDOW_SCALE

#endif
